#! /bin/sh
#
# putinbin
#
XSTART=0.0
XSTOP=20.0
BINLEN=0.5
nawk ' 
BEGIN { x=xstart; cum=0; }
((x < $1 ) && ( $1 <= (x+binlen) )) { cum += $2; next; }
{ print x," ",cum; 
  x += binlen; 
  print x," ",cum;
  cum = 0;
  while( x+binlen < $1 ) { print x," ",cum; x += binlen; print x," ",cum; }
  cum = $2;
  if ( x > xstop ) { exit 0; } 
}
' xstart=$XSTART xstop=$XSTOP binlen=$BINLEN
