files: ../BSEpp.eps \
       ../dyson.eps \
       ../BSEph.eps 

../dyson.eps: dyson.C
	FD -o ../dyson.eps dyson

../BSEpp.eps: BSEpp.C
	FD -o ../BSEpp.eps BSEpp

../BSEph.eps: BSEph.C
	FD -o ../BSEph.eps BSEph
