#! /bin/sh
#
# addxy xyfile1 xyfile2
FAC1=1.0
FAC2=1.0
case $# in
4) FAC2=$4
   ;;
3|4) FAC1=$3
   ;;
2|3|4) ;;
*) echo usage addxy xyfile1 xyfile2 [fac1 [fac2]]
esac
#
#
#
paste $1 $2 |
nawk 'NF == 4 { if( abs($1-$3)<0.01 ) {
                 print $1," ", fac1*$2+fac2*$4
               } else { print "error" ; exit }
             }
function abs(s) { if( s<0 ) {return (-s);} else {return(s);}}
' fac1=$FAC1 fac2=$FAC2

