PSFILES= 	hhptda1.ps \
		hhptda2.ps \
		hhptda.ps \
		pphtda.ps \
		sig_2nd.ps \
		sig_HF.ps  \
		sig_UHF.ps \
		sig_UHF1.ps\
		sig_UHF2.ps\
		sig_UHF3.ps

.SUFFIXES: .C .ps
.C.ps:
	FD -o $*.ps $*

all: $(PSFILES)

